/*
 * This file is generated by jOOQ.
 */
package ru.springauth.adapters.db.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.springauth.adapters.db.jooq.tables.AuthUser;
import ru.springauth.adapters.db.jooq.tables.Databasechangeloglock;
import ru.springauth.adapters.db.jooq.tables.records.AuthUserRecord;
import ru.springauth.adapters.db.jooq.tables.records.DatabasechangeloglockRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthUserRecord> AUTH_USER_PKEY = Internal.createUniqueKey(AuthUser.AUTH_USER, DSL.name("auth_user_pkey"), new TableField[] { AuthUser.AUTH_USER.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
}
