server:
  port: 8080
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://127.0.0.1:5100/simple_auth
    password: simple_auth
    username: simple_auth
  liquibase:
    change-log: "classpath:db/master.xml"
    enabled: true

app:
  tokens:
    remember-me-token-validity-duration: 24h
    reset-password-token-validity-duration: 1d
  allowedOrigins: http://localhost
  auth:
    secret: auth_secret
